### ISSUE TITLE
Source Code to SqlTokenizer

### ISSUE THREAD

**Issue by mbhildebrand** [ronymmoura/sql-formatter#2]
Hi Rony!
I'm trying to compile and build your SQLFormatter from just the source code.  It looks like the project is missing the SQLTokenizer code?  I don't want the DLL, I'd like the source code if that is available.

Thanks!  Michael

**Comment by mbhildebrand** [comment]
Thanks Rony - I found it.

**Comment by DarthVader85PA** [comment]
Hi @mbhildebrand
Perhaps you can help me: where is the source code for `SQLTokenizer`.
Do you have the source code, if it not online available?
Greetings from Germany

**Comment by ronymmoura** [comment]
Hi @DarthVader85PA. The code for the SQLTokenizer can be found here: https://github.com/ronymmoura/sql-tokenizer
It's in a separated repo because I use it in another project that translates MSSQL queries to Oracle queries
